### ISSUE TITLE
std::list, std::deque support?

### ISSUE THREAD

**Issue by hdclark** [p-ranav/alpaca#11]
Awesome project!

Are std::list and/or std::deque supported?

**Comment by hdclark** [comment]
@p-ranav Any comment?

I would love to use this for a nested struct that contains a std::list, but list support is suspiciously absent from the examples and documentation.

If absent, is it just a preference, or is there some incompatibility with Python?

**Comment by p-ranav** [comment]
I'll add support for `std::list` and `std::deque` soon. As for Python, I'd probably just support it with `collections.deque`, TBD.

**Comment by hdclark** [comment]
Awesome!!
