### ISSUE TITLE
cross-compilation for embedded bare-metal environment

### ISSUE THREAD

**Issue by daniel-merrick** [p-ranav/alpaca#13]
Hi @p-ranav , 

Would you be able to provide a list of instructions for cross-compiling to bare metal platform?

I'm using the following toolchain:

```
GNU Arm Embedded Toolchain 2021.07
Pre-built GNU toolchain for Arm Cortex-A/R and Cortex-M processors
GCC Version: 10.3
```

With this toolchain I get the following error:

`./include/alpaca/detail/crc32.hpp:73:2: error: #error unsupported system
   73 | #error unsupported system`

Thanks!

**Comment by p-ranav** [comment]
Do you have access to `<sys/param.h>` header in your platform? If so you can just define the system as `__gnu_linux__` and it should work. This is what I did when developing for the ESP32 processor. 

```cpp
#define __gnu_linux__
#include <alpaca/alpaca.h>
```

If this is not the case, then we need to define an `elif` case for bare metal, that defines `__ALPACA_BYTE_ORDER` and `ALPACA_PREFETCH` defines. 

```cpp
#if ...
...
...

/// Define the following part
#elif defined(__BARE_METAL_PLATFORM__) /// How to check if platform is bare metal?

#define __ALPACA_BYTE_ORDER 1234  /// little endian
#define ALPACA_PREFETCH(location) ; /// No prefetching

#else
#error unsupported system
#endif
```

**Comment by daniel-merrick** [comment]
Awesome thanks for the response, closing issue.
