### ISSUE TITLE
Problem of using alpca if my structure contains constructor 

### ISSUE THREAD

**Issue by jackgoodman2** [p-ranav/alpaca#24]
I found the compiler will give a dead error if my structure or class has constructor function? Anyone met this problem and know how to address it?

**Comment by p-ranav** [comment]
Can you provide an example? Does your struct have a default constructor? One might be necessary. 

This worked for me:

```cpp
// test.cpp
#include <alpaca/alpaca.h>

struct Config {
  Config() = default;
  Config(const std::string &device) : device(device) {}
  std::string device;
};

int main() {

  // Construct the object
  Config c("/dev/video0");

  // Serialize
  std::vector<uint8_t> bytes;
  auto bytes_written = alpaca::serialize(c, bytes);

  // Deserialize
  std::error_code ec;
  auto object = alpaca::deserialize<Config>(bytes, ec);
  if (!ec) {
    // use object
    std::cout << object.device << "\n";
  }
}
```

```console
foo:bar$ ./test
/dev/video0
```

**Comment by jackgoodman2** [comment]
ranav, 

Thanks for your kind reply. 
I found your examples works fine for me. In my example, the default example of write_file.cpp, I added  GameState() {} as the constructor, it gives me an error when compiling, but after I changed to  GameState() = default; it can successfully be compiled. I think your example solved my problem.

Many thanks.

**Comment by p-ranav** [comment]
Sounds good, glad it worked.

**Comment by jackgoodman2** [comment]
ranav, 
for the following structure, the compiler gives me an error, Error C3448 The number of identifiers must match the number of array elements or members in the structured binding declaration. Can you help me figure out where the error came from? All the data type in the following stuctures are same to that in alpaca, for instance, Int is int64_t, Real is double and so on

struct edge_type {
    // edge element type
    // Line2 or line3
    elem_type type = elem_type::LINE2;
    // main node count on the edge, exclude quadratic points
    Int nnode = EDGE_NODE_SIZE;
    // base node list
    // anticlockwise, same with element
    Int node[EDGE_NODE_SIZE];
    // parent element belong to, its id if it is surface
    Int element = -1;
    // parent CZM
    Int CZM = -1;
    // centeric point, will not be updated
    // for octree
    Vector2 coord;
    // the other edge id, -1 is boundary
    Int pair = -1;
    // DFN id, default -1, otherwise the DFN id in dfn
    Int DFN = -1;
    // bool of surface element
    bool iselement = false;
    // bool of quadratic
    bool isquadratic = false;
    // bool of quadratic
    Int quadnode = -1;
  
    edge_type() = default;
};

typedef struct Edge_structure* Edge;

struct Edge_structure {
    // count of the edge
    UInt nedge = 0;
    // edges structure for 2D elements
    std::vector<edge_type> edges;

    // resize the nodal container
    void resize(Int size, Int initialsize = 0);
    // clear the nodal container
    void clear();
};

**Comment by jackgoodman2** [comment]
Is the reason alpaca doesn't support raw array? I should change node[EDGE_NODE_SIZE] to std::array<Int,EDGE_NODE_SIZE> node?
