### ISSUE TITLE
Docs: Add example of own type serealization

### ISSUE THREAD

**Issue by lolpie244** [p-ranav/alpaca#38]
Unfortunately, not all types are supported by this library. The one example is glm vectors. So it would be useful to have guide how to add own types.

@p-ranav, If you don't mind, I will be able to add serealization of glm vector as an example

**Comment by p-ranav** [comment]
Sure, feel free to create a PR to support glm types. But please wrap this in a `ALPACA_INCLUDE_SUPPORT_GLM_VECTOR` macro `ifdef`, which when defined, can include the glm header(s) and enable support. Since not everyone has the glm library, I'd like for this to be an opt-in.

**Comment by lolpie244** [comment]
@p-ranav, I encounter a strange bug: code below throw error "Value too large for defined data type"

```cpp
struct Data {
  int id;
  std::vector<uint8_t> vec;
};

int main() {
  Data data;

  for (int i = 0; i < 10; i++)
    data.vec.push_back(i);

  std::vector<uint8_t> bytes;
  alpaca::serialize(data, bytes);

  std::error_code ec;
  data = alpaca::deserialize<Data>(bytes, ec);
  std::cout << ec.message() << '\n';
}
```
Could you please advice, what shoud I do in this situation?

**Comment by lolpie244** [comment]
@p-ranav, sorry for the long response. Fixed

**Comment by p-ranav** [comment]
No worries, thanks! I've merged it, closing now.
